/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List detection rules */
        get: {
            parameters: {
                query?: {
                    /** @description Filter by rule origin. */
                    source?: "all" | "builtin" | "custom";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Rule list. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            rules?: components["schemas"]["Rule"][];
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
            };
        };
        put?: never;
        /**
         * Create a custom rule
         * @description The rule is validated with the production compile path (RE2 regex,
         *     known validators, capture-group bounds, bounded placeholder) before
         *     being persisted and atomically applied to the running rule set.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Rule"];
                };
            };
            responses: {
                /** @description Rule created and active. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Rule"];
                    };
                };
                400: components["responses"]["BadRequest"];
                /** @description A rule with this rule_id already exists (custom or built-in). */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Bulk enable or disable rules
         * @description Enable or disable many rules in one call. Best-effort: each id is attempted independently and its outcome reported per item, so a single failure does not abort the batch (HTTP 200 with per-item status). Built-in rules accept only the enable/disable toggle.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["BulkPatch"];
                };
            };
            responses: {
                /** @description Per-rule outcomes. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BulkPatchResult"];
                    };
                };
                400: components["responses"]["BadRequest"];
            };
        };
        trace?: never;
    };
    "/v1/rules/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Get one rule (built-in or custom) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The rule. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Rule"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        /** Replace a custom rule */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Rule"];
                };
            };
            responses: {
                /** @description Rule updated and active. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Rule"];
                    };
                };
                400: components["responses"]["BadRequest"];
                404: components["responses"]["NotFound"];
                /** @description Built-in rules are immutable via the API. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        post?: never;
        /** Delete a custom rule */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Rule deleted. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: components["responses"]["NotFound"];
                /** @description Built-in rules are immutable via the API. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /**
         * Enable or disable a rule (built-in or custom)
         * @description Toggles whether the rule participates in scanning. This is the only mutation permitted on built-in rules. Idempotent; disabled rules stay listed with `enabled: false` and are excluded from the compiled rule set on all replicas after the rules refresh interval.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RulePatch"];
                };
            };
            responses: {
                /** @description The rule with its new enabled state. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Rule"];
                    };
                };
                400: components["responses"]["BadRequest"];
                404: components["responses"]["NotFound"];
            };
        };
        trace?: never;
    };
    "/v1/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get global guardrails settings */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Current settings. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Settings"];
                    };
                };
            };
        };
        /** Replace global guardrails settings */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Settings"];
                };
            };
            responses: {
                /** @description Settings saved and applied. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Settings"];
                    };
                };
                400: components["responses"]["BadRequest"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/data-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List data-type groups */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Data types declared in the rule files plus CUSTOM. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data_types?: components["schemas"]["DataType"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Dry-run scan (rule tester)
         * @description Scan sample text through the production compile + scan + mask path without persisting masking state or calling any upstream. Optionally supply a not-yet-saved candidate_rule to test it against the built-in rules before saving. Returns triggered rules/data types, the masked text and the placeholder substitutions.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ScanRequest"];
                };
            };
            responses: {
                /** @description Scan result. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ScanResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Build identity and topology */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Version, build metadata, topology, store backend and live mode. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Version"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness of the configuration API
         * @description Lightweight liveness signal on the config port. Reaching it means the API server is up; also echoes the live mode and store backend. For ext_proc-guardrails this is the only HTTP health endpoint (the data path is gRPC).
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Service is up. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Health"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/metrics/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Aggregated metrics summary
         * @description JSON aggregates of the registered Prometheus counters and histograms, so the console can show lifetime numbers without a Prometheus/Grafana stack. Latency quantiles are approximate (interpolated from histogram buckets).
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Metrics summary. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MetricsSummary"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/audit/records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List masking audit records
         * @description Per-request masking audit trail: which rules and data types fired
         *     and which placeholders replaced the detected values. Records never
         *     contain the original sensitive values; `masked_texts` is present
         *     only when the service runs with
         *     `GUARDRAILS_AUDIT_STORE_MASKED_TEXTS=true`.
         *
         *     Served only when `GUARDRAILS_AUDIT_ENABLED=true`; otherwise the
         *     route does not exist (404). Newest records first; paginate with the
         *     opaque `cursor` from the previous response. With the redis backend a
         *     heavily filtered query may return fewer than `limit` records together
         *     with a cursor — keep paging until `next_cursor` is absent.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Exact model match (x-gateway-model-name). */
                    model?: string;
                    /** @description Exact request path match. */
                    path?: string;
                    /** @description Only records where this rule triggered. */
                    rule_id?: string;
                    /** @description Only records where this data type triggered; number or name. */
                    data_type?: string;
                    /** @description Inclusive lower bound (RFC3339). */
                    since?: string;
                    /** @description Exclusive upper bound (RFC3339). */
                    until?: string;
                    /** @description Page size, capped at 500. */
                    limit?: number;
                    /** @description Opaque pagination cursor from a previous response. */
                    cursor?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description One page of audit records. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuditRecordList"];
                    };
                };
                400: components["responses"]["BadRequest"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/audit/records/{request_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the audit record of one request
         * @description Served only when `GUARDRAILS_AUDIT_ENABLED=true`.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The x-request-id of the audited request. */
                    request_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The audit record. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuditRecord"];
                    };
                };
                /** @description No audit record for this request id (never masked, expired or audit disabled). */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Rule: {
            rule_id: string;
            name: string;
            group?: string;
            /** @description 1=CREDENTIALS 2=API_KEYS 3=ACCESS_TOKENS 4=IP_ADDRESSES 5=PERSONAL_DATA 6=CUSTOM */
            data_type: number;
            /** @description RE2 regular expression. */
            regex: string;
            /** @description Case-insensitive pre-filter; the regex only runs when a keyword is present. */
            keywords?: string[];
            validators?: ("luhn" | "snils" | "inn_person" | "inn_org" | "ogrn" | "ogrnip" | "iban_mod97" | "email_ascii" | "payment_card" | "entropy" | "banlist" | "ip_v4" | "ip_v6" | "ip_public" | "ip_private")[];
            min_length?: number;
            /** @description Minimum Shannon entropy for the entropy validator. */
            entropy?: number;
            banlist?: string[];
            masking: {
                /** @description 1-based capture groups to mask; empty masks the full match. */
                capture_groups?: number[];
                /** @description Placeholder type; detected values become `<PLACEHOLDER_N>`. */
                placeholder?: string;
            };
            /** @enum {string} */
            readonly source?: "builtin" | "custom";
            /** @description false when the rule is disabled via PATCH /v1/rules/{id}; disabled rules are excluded from scanning. */
            readonly enabled?: boolean;
        };
        RulePatch: {
            enabled: boolean;
        };
        BulkPatch: {
            /** @description Rule ids to toggle. */
            ids: string[];
            /** @description Applied to every id. */
            enabled: boolean;
        };
        BulkPatchResult: {
            results?: components["schemas"]["BulkPatchItem"][];
        };
        BulkPatchItem: {
            rule_id?: string;
            /** @enum {string} */
            status?: "ok" | "error";
            /** @description Present when status is error. */
            error?: string;
        };
        Settings: {
            enabled: boolean;
            /** @description Accepts numbers or names on input; always numbers on output. */
            data_types: (number | string)[];
            /**
             * @description enforce masks traffic; detect (shadow mode) scans and records metrics/audit but never mutates request or response bodies. PUT replaces the whole settings document — omitting mode resets it to enforce.
             * @default enforce
             * @enum {string}
             */
            mode: "enforce" | "detect";
        };
        DataType: {
            data_type?: number;
            name?: string;
            display_name?: string;
            description?: string;
        };
        /** @description Provide either text (one sample) or texts (several). */
        ScanRequest: {
            text?: string;
            texts?: string[];
            /** @description Narrows the scan; empty means all known. Numbers or names. */
            data_types?: (number | string)[];
            candidate_rule?: components["schemas"]["Rule"];
        };
        ScanResponse: {
            /** @description One masked text per input, in order. */
            masked_texts?: string[];
            triggered_rule_ids?: string[];
            triggered_data_types?: number[];
            placeholders?: components["schemas"]["Placeholder"][];
            timings?: {
                total_ms?: number;
            };
        };
        /** @description One original→placeholder substitution from the scanned sample. */
        Placeholder: {
            placeholder?: string;
            original?: string;
            rule_id?: string;
        };
        Version: {
            version?: string;
            commit?: string;
            date?: string;
            /** @enum {string} */
            mode?: "enforce" | "detect";
            store_backend?: string;
            /** @enum {string} */
            topology?: "standalone" | "ext_proc";
        };
        Health: {
            status?: string;
            /** @enum {string} */
            mode?: "enforce" | "detect";
            store_backend?: string;
        };
        MetricsSummary: {
            /** @description Total masked requests keyed by mode (enforce/detect). */
            requests_masked_total?: {
                [key: string]: number;
            };
            rule_triggers_total?: components["schemas"]["LabelCount"][];
            data_type_triggers_total?: components["schemas"]["LabelCount"][];
            passthrough_total?: {
                [key: string]: number;
            };
            latency_seconds?: {
                [key: string]: components["schemas"]["Latency"];
            };
        };
        LabelCount: {
            label?: string;
            count?: number;
        };
        /** @description Sample count and bucket-interpolated (approximate) quantiles. */
        Latency: {
            count?: number;
            p50?: number;
            p95?: number;
        };
        AuditRecord: {
            request_id?: string;
            /**
             * Format: date-time
             * @description Microsecond precision, UTC.
             */
            timestamp?: string;
            /**
             * @description The guardrails mode in effect when the request was recorded.
             *     `detect` records were scanned but the body was not mutated.
             * @enum {string}
             */
            mode?: "enforce" | "detect";
            model?: string;
            path?: string;
            triggered_rule_ids?: string[];
            triggered_data_types?: number[];
            replacements?: components["schemas"]["AuditReplacement"][];
            /**
             * @description Post-masking request texts (placeholders substituted, originals
             *     absent). Present only when the service stores masked texts.
             */
            masked_texts?: string[];
            /**
             * @description Post-masking model response texts (placeholders substituted,
             *     originals absent) — the response counterpart of `masked_texts`.
             *     Present only when the service scans and stores masked responses.
             */
            masked_response_texts?: string[];
        };
        /** @description One masked value. The original is exposed only when the backend opts in via GUARDRAILS_AUDIT_STORE_ORIGINAL_TEXTS (off by default); otherwise the `original` field is absent. */
        AuditReplacement: {
            rule_id?: string;
            /** @description 0 when the rule was deleted before the record was written. */
            data_type?: number;
            /** @description The placeholder that replaced the value, e.g. `<EMAIL_1>`. */
            placeholder?: string;
            /** @description The raw pre-masking value behind `placeholder`. Present only when the backend is configured to store originals; used by the UI to reveal the value on hover. */
            original?: string;
        };
        AuditRecordList: {
            records?: components["schemas"]["AuditRecord"][];
            /** @description Present while more pages exist; pass back as `cursor`. */
            next_cursor?: string;
        };
        Error: {
            error?: string;
            details?: string;
        };
    };
    responses: {
        /** @description Validation error. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description No such rule. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
